---
title: "Case Study 04"
author: Eleanor M. Byrne 
date: August 1, 2020
output: github_document
---

## Packages/Lib

Comments

```{r}
# This is for library/packages
# install/load packages 
library(tidyverse)
# install.packages('nycflights13')
library(nycflights13)
library(dplyr)
```

## Opening/Data/information

```{r}
# Open and access the nyc flights 
airports <- nycflights13::airports
flights <- nycflights13::flights
```

```{r}
# Find the maximum distance and the corresponding destination airport code
highest <- flights %>%
  arrange(desc(distance)) %>%
  slice(1) %>% 
  select(dest, distance)
# It would be HNL (dest)
```

```{r}
# Join with airports data to get the full name of the airport
farthest_airport_data <- highest %>%
  left_join(airports, by = c("dest" = "faa")) %>%
  select(name) # select the the destName column only 
```

```{r}
# Convert the data.frame to a single character value with as.character()
farthest_airport <- as.character(farthest_airport_data$name)
# Print the farthest airport name
farthest_airport
```
